# https://docs.gitlab.com/ee/ci/yaml/#before_script-and-after_script
# https://docs.gitlab.com/ee/ci/docker/using_docker_images.html#define-image-and-services-from-gitlab-ciyml

# Official language image. Look for the different tagged releases at:
# https://hub.docker.com/r/library/rust/tags/
# image: "rust:latest"

# Run tests with cargo
# single threaded version of running tests
#- cargo test --all --verbose -- --test-threads=1  
test:x86_64:
  image: "rust:latest"
  script:
  - rustc --version && cargo --version # Print version info for debugging
  - cargo test --all --verbose  # Not single threaded since this is running on x86_64
  

build:arm:
  image: "rust:latest"
  before_script:
    - dpkg --add-architecture armhf
    - apt-get update -yqq
    - apt-get install -yqq build-essential gcc-arm-linux-gnueabihf libsqlite3-dev:armhf
    - rustup target add armv7-unknown-linux-gnueabihf
  script:
    - RUSTFLAGS="-C linker=arm-linux-gnueabihf-gcc" cargo build --target=armv7-unknown-linux-gnueabihf
