# https://docs.travis-ci.com/user/languages/rust/

language: rust
sudo: required

rust:
  - stable
  - beta
  - nightly

matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true

jobs:
  include:
    - stage: test
      script:
        - cargo test --verbose --all
    - stage: clippy
      before_script:
        - rustup component add clippy
      script:
        - cargo clippy
