# https://docs.travis-ci.com/user/languages/rust/

language: rust

sudo: required

rust:
  - stable
  - beta
  - nightly

matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true

script:
  - cargo test --verbose --all
