[package]
name = "raspberry-web"
version = "0.1.2"
authors = ["bogeholm <troelsmikkelsen@gmail.com>"]

[dependencies]
actix = "0.7.4"
actix-web = "0.7.8"
chrono = { version = "0.4.6", features = ["serde"] }
diesel = { version = "1.3.0", features = ["sqlite", "chrono", "r2d2"] }
dotenv = "0.13.0"
env_logger = "0.5.13"
futures = "0.1"
log = { version = "0.4", features = ["std", "serde"] }
r2d2 = "0.8.2"
r2d2-diesel = "1.0.0"
serde="1.0"
serde_derive="1.0.79"
serde_json="1.0"



