[package]
name = "raspberry-web"
version = "0.1.0"
authors = ["bogeholm <troelsmikkelsen@gmail.com>"]
edition = "2018"
license = "MIT"
description = "Control the GPIO pins on your Raspberry Pi with a simple web service. Currently supports output only."

[dependencies]
actix = "0.7.9"
actix-web = "0.7.17"
chrono = { version = "0.4.6", features = ["serde"] }
diesel = { version = "1.3.0", features = ["sqlite", "chrono", "r2d2"] }
diesel_migrations = "1.3.0" # For tests
dotenv = "0.13.0"
env_logger = "0.6.0"
futures = "0.1"
log = { version = "0.4", features = ["std", "serde"] }
parking_lot = "0.6"
r2d2 = "0.8.2"
r2d2-diesel = "1.0.0"
serde="^1.0.82"
serde_derive="^1.0.82"
serde_json="^1.0.33"

[target.armv7-unknown-linux-gnueabihf.dependencies]
rppal = "0.9.0"

