[package]
name = "raspberry_web"
version = "0.1.2"
authors = ["bogeholm <troelsmikkelsen@gmail.com>"]
#edition = "2018"

[dependencies]
actix = "0.7.7"
actix-web = "0.7.14"
chrono = { version = "0.4.6", features = ["serde"] }
diesel = { version = "1.3.0", features = ["sqlite", "chrono", "r2d2"] }
diesel_migrations = "1.3.0" # For tests
dotenv = "0.13.0"
env_logger = "0.6.0"
futures = "0.1"
log = { version = "0.4", features = ["std", "serde"] }
r2d2 = "0.8.2"
r2d2-diesel = "1.0.0"
#rppal = "0.9.0"
serde="1.0"
serde_derive="1.0.79"
serde_json="1.0"



