[package]
name = "raspberry-web"
version = "0.1.0"
authors = ["bogeholm <troelsmikkelsen@gmail.com>"]

[dependencies]
chrono = { version = "0.4.6", features = ["serde"] }
diesel = { version = "1.3.0", features = ["sqlite"] }
dotenv = "0.13.0"
env_logger = "0.5.13"
log = { version = "0.4", features = ["std", "serde"] }
serde="1.0"
serde_derive="1.0.79"
serde_json="1.0"



